export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/discover/index',
    'pages/profile/index',
    'pages/create/index',
    'pages/detail/index',
    'pages/dimension-edit/index',
    'pages/tasks/index',
    'pages/quiz/index',
    'pages/dates/index',
    'pages/date-edit/index',
    'pages/portrait/index',
    'pages/user-profile/index',
    'pages/interactions/index',
    'pages/interaction-create/index',
    'pages/interaction-detail/index',
    'pages/knowledge-detail/index',
    'pages/knowledge-cycle/index',
    'pages/knowledge-icebreaker/index',
    'pages/knowledge-scenario/index',
    'pages/speed-plan/index',
    'pages/speed-plan-list/index',
    'pages/story/index',
    'pages/story-list/index',
    'pages/moments/index',
    'pages/moments-create/index',
    'pages/moments-analyze/index',
    'pages/moments-history/index',
    'pages/dating-app/index',
    'pages/dating-profile/index',
    'pages/dating-photo/index',
    'pages/dating-opener/index',
    'pages/interactive-games/index',
    'pages/game-truth-dare/index',
    'pages/game-understand/index',
    'pages/game-tacit/index',
    'pages/game-scenario/index',
    'pages/game-quick/index',
    'pages/game-challenge/index',
    'pages/game-touch/index',
    'pages/game-mirror/index',
    'pages/game-pulse/index',
    'pages/game-blind/index',
    'pages/game-distance/index',
    'pages/game-breath/index',
    'pages/grow/index',
    'pages/cycle/index',
    'pages/chat-review/index',
    'pages/date-plan/index',
    'pages/sweet-talk/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#FFFFFF',
    navigationBarTitleText: '知拌',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#9CA3AF',
    selectedColor: '#4ECB71',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '对象',
        iconPath: './assets/tabbar/users.png',
        selectedIconPath: './assets/tabbar/users-active.png',
      },
      {
        pagePath: 'pages/discover/index',
        text: '发现',
        iconPath: './assets/tabbar/sparkles.png',
        selectedIconPath: './assets/tabbar/sparkles-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: './assets/tabbar/user.png',
        selectedIconPath: './assets/tabbar/user-active.png',
      },
    ],
  },
})
